version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: itp-db
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data: